INSERT INTO Human(Name, Surname, Patronymic, Birthday, Country, Sex) VALUES(N'Василий', N'Калашников', N'Петрович','12/30/1991', N'Российская Федерация', N'Мужчина')
INSERT INTO Human(Name, Surname, Patronymic, Birthday, Country, Sex) VALUES(N'Муса', N'Оздемиров', N'Албекович','09/21/2002', N'Таджикистан', N'Мужчина')
INSERT INTO Human(Name, Surname, Patronymic, Birthday, Country, Sex) VALUES(N'Антон', N'Мартынов', N'Львович','02/15/1987', N'Республика Беларусь', N'Мужчина')
INSERT INTO Human(Name, Surname, Patronymic, Birthday, Country, Sex) VALUES(N'Адиль', N'Жалелов', N'Оралбекович','08/03/1989', N'Казахстан', N'Мужчина')
INSERT INTO Human(Name, Surname, Patronymic, Birthday, Country, Sex) VALUES(N'Сердар', N'Бердымухамедов', N'Гурбангулыевич','09/22/1981', N'Туркмения', N'Мужчина')
INSERT INTO Human(Name, Surname, Patronymic, Birthday, Country, Sex) VALUES(N'Муслим', N'Магомаев', N'Магометович','08/17/1989', N'Азербайджан', N'Мужчина')
INSERT INTO Human(Name, Surname, Patronymic, Birthday, Country, Sex) VALUES(N'Анастасия', N'Каменских', N'Алексеевна','04/05/1987', N'Украина', N'Женщина')
INSERT INTO Human(Name, Surname, Patronymic, Birthday, Country, Sex) VALUES(N'Ильзат', N'Ахметов', N'Тоглокович','12/31/1997', N'Кыргызстан', N'Мужчина')
INSERT INTO Human(Name, Surname, Patronymic, Birthday, Country, Sex) VALUES(N'Гарик', N'Мартиросян', N'Юрьевич','02/14/1974', N'Армения', N'Мужчина')
INSERT INTO Human(Name, Surname, Patronymic, Birthday, Country, Sex) VALUES(N'София', N'Ротару', N'Михайловна','08/07/1947', N'Молдавия', N'Женщина')